name: Translate CV to English

on:
  push:
    branches: [main]
    paths: ["index.html"]

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install openai

      - name: Run translation script
        run: python translate_cv.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit translated file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add cv_en.html
          git commit -m "Auto-translate CV to English"
          git push
